version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      CLIENT_URL: http://localhost:5173
      JWT_SECRET: local-dev-secret
      DATABASE_URL: file:./dev.db
